.\" Manpage for _printf.
.TH _printf 3 "28 March 2023" "1.0" "Program Manual for _printf"
.SH NAME
_printf - formatted output conversion and print data.
.SH SYNOPSIS
.nf
.BI printf (FORMAT, ARGUMENT)...
.PP
.SH DESCRIPTION
The output function _printf() produce output according to a format. the function _printf converts the character strings that receives as argument and prints it on the standard output.
.SH RETURN VALUE
Returns the number of all the characters printed, excluding the NULL byte used to end output to strings.
.SH SEE ALSO
.R printf(3)
.SH AUTHORS
Written by \fBNadene Samuels\fR and \fBNkosinathi Msubo\fR.
